<a href="https://colab.research.google.com/github/vichacker1234/Proyectos_IA/blob/main/Librer%C3%ADa_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Cargar la librería**


In [1]:
#Primero se carga la librería numpy
import numpy as np

##Creación de arrays

Vamos a crear arrays de distintas dimensiones. Para esto podemos usar números, listas o tuplas.

In [15]:
#array de dimensión 0
a=np.array(13)
#array de dimensión 1
b=np.array([1,2,3,4])
#array de dimensión 2
c=np.array([[1,2,3,4],[5,6,7,8]])
#array de dimensión 3
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) 

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")


a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



**Análisis de las dimensiones**
Se van a observar las dimensiones de cada uno de los arrays


In [19]:
#Dimensión array a (0)
print(a.ndim)
#Dimensión array b (1)
print(b.ndim)
#Dimensión array c(2)
print(c.ndim)
#Dimesión array d(3)
print(d.ndim)

0
1
2
3


**Indexación básica**

El proceso de indexación en numpy es similar al de las listas en python. Cada número implica buscar la posición en cada dimensión del array

In [26]:
#Indexación o filtrado de los elementos del array (a)
print('a=',a)
#imprime el tercer elemento del array (0,1,2) en este caso eb b
print("b[2] = ",b[2])
#Tenemos otro ejemplo sobre el mismo array
print("b[3]=",b[3])
#Se imprime el segundo elemento del array c(En este caso una fila de una matriz)
print("c[1] =",c[1])
#Se imprime el segundo elemento del array d (En este caso una matriz)
print("d[1] =",d[1])

a= 13
b[2] =  3
b[3]= 4
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


In [31]:
#Imprime el elemento del array a
print("a =",a)
#Imprime el tercer elemento del array b
print("b[2] =",b[2])
#imprime el elemento que está en el segundo componente de c y en el tercer componente de la fila 2 
print("c[1,2] =",c[1,2])
#Imprime la segunda submatriz, primera fila y tercer componente
print("d[1,0,2] =",d[1,0,2])


a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


**Segmentar arrays**

Similarmente podemos segmentar arrays como en el las listas de python,

In [36]:
#Imprime los elementos de la posición 2 a la 4
#b = [1 2 3 4] 
print(b[1:4]) 
#Imprime los elemento 6 y 7 de la segunda fila
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 



[2 3 4]
[6 7]


**Diferentes tipos de datos en los arrays**

Los arrays no están limitados a números enteros, pueden también tener cadenas, booleanos, o de punto flotante.

In [43]:
#Un array de caracteres con nombre de frutas 
frutas = np.array(['Manzana', 'Naranja', 'Uva']) 
#Muestra el array
print(frutas)
#Muestra el tipo de array
print(type('frutas'))
#cadenas
print(frutas.dtype)

['Manzana' 'Naranja' 'Uva']
<class 'str'>
<U7


Podemos manipular el tipo de los datos del array dentro de la función de creación del array np.array, siempre y cuando el cambio sea posible. Por ejemplo podemos pasar enteros a cadenas (integers a strings) pero no viceversa.

In [48]:
#Transformamos los números a caracteres 
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)

print(number_to_string)

#Se puede verificar el tipo
print(type('number_to_string'))
#Tipo string

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']
<class 'str'>


In [49]:
try:
    error_array = np.array(['a', '2', '3'], dtype='i')
except:
    print("hay un error en su lógica")

hay un error en su lógica


Podemos también cambiar el tipo en arrays ya existentes

In [51]:
floating_array = np.array([1.1, 2.1, 3.1]) #punto flotante (Números reales)
#transformarlo a un array entero
int_array = floating_array.astype('i')
print(int_array)

[1 2 3]


**Forma de los arrays**

La forma es distinta a la dimensión. Esta se define como el número de elementos de la dimensión.

In [52]:

print(a.shape) # a = 13 
#4 elementos en la dimensión 1
print(b.shape) # b = [1 2 3 4] 
#2 elementos en la  dimensión 1 y 4 elementos en la dimensión 2
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
#2 elementos en la dimensión 1, 2 elementos en la dimensión 2 y 4 elementos en la dimensión 3
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


**Reformar arrays**

Podemos cambiar la forma de los arrays. Esto significa aumentar el número de dimensiones o cambiar cuantos elementos hay por dimensión

In [53]:
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



¿Podemos hacer cualquier cambio en la forma? Si, mientras las que se quieren conseguir coincidan con la cantidad de elementos.

In [54]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


d es un array con 16 elementos, así que podemos hacer reshape con tamaños por ejemplo 1x16, 4x4, 8x2, 2x4x2 Por ejemplo, no podemos reformar un arrey a 3x5.

In [55]:
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones')

Hay un error en sus operaciones


In [56]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

**Dimensión desconocida**

Podemos definir el cambio de forma con una dimensión la cual no sabemos el tamaño. Numpy se encargará de definir el tamaño que mejor se ajuste.

In [63]:
#Arreglo de números arbitrario  en python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos usar la dimensión desconocida para "aplanar" el array a una dimensión.

In [64]:
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

**Transpuesta**

Para transponer el array utilizamos .T

In [66]:
#Imprime el array con salto de linea
print("c =",c,"\n")
#Imprime la matriz transpuesta de c
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


Iterar arrays
Podemos usar los métodos tradicionales para iterar.

In [72]:
#Estructura de control
#Itera los elementos de x en d
for x in d:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


**Iteraciónes por cada dimensión**


Si queremos iterar cada elemento, necesitamos un for por cada dimensión

In [73]:
#Itera primero sobre las dimesiones de d(3)
#Itera sobre elemento  de d (filas)
#Itera sobre cada elemento de la fila
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


Esto por supuesto no es óptimo. Así que numpy tiene la función nditer() para estos casos.

In [74]:
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


**Aplicar operaciones entre arrays**

numpy tiene sus propias formas de aplicar operaciones:

Suma
numpy tiene dos funciones, np.add() y np.sum(). El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma

In [77]:
#Se tienen los array
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
#Se suman los elementos de cada array (Como una suma entre matrices)
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [81]:
#Se define este nuevo array
arr3=np.array([[1,1,1],[1,1,1]])
print(arr3)
#Suma los elementos de cada array entre sí
#En ete caso suma desde el 1 hasta el 2 en cada array, lo que nos da 42
print(np.sum([arr1,arr2]))
#Suma de los elementos de cada array entre sí ( En este caso se obtiene 48)
print(np.sum([arr1,arr2,arr3]))

[[1 1 1]
 [1 1 1]]
42
48


**Multiplicación Matricial**

Para la multiplicación de matrices usamos np.matmul() o np.dot(). hay que tener en cuenta la forma de las 

In [83]:
#Multiplica la matriz arr1 con la transpuesta de arr2
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [85]:
#También se puede obtener de esta manera
np.dot(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

Se comportan distinto con matrices de dos dimensiones, para otros casos hacen cosas distintas

In [86]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [92]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")


[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



Con matmul no se pueden multiplicar escalares c.A (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con dot, donde este toma los números dentro de las matrices como elementos.

In [94]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])